# Change these first
owner: null-qwerty # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: blog
    url: https://blog.null-qwerty.work
  - name: images
    url: https://images.null-qwerty.work/large_evcg11c.png

status-website:
  theme: light
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.null-qwerty.top
  # baseUrl: /your-repo-name
  logoUrl: https://images.null-qwerty.work/blog/avatar.jpg
  name: status
  introTitle: "**状态面板**"
  introMessage: "~~今日水逆~~"
  navbar:
    - title: blog
      href: https://blog.null-qwerty.work
    - title: GitHub
      href: https://github.com/$OWNER

workflowSchedule:
  graphs: "0 * * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 * * * *"
  updateTemplate: "0 * * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
